apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-todo-deployment
  labels:
    app: django-todo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: django-todo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        app: django-todo
    spec:
      containers:
      - name: django-todo-container
        image: prathmeshj476/django-todo:9
        imagePullPolicy: Always  # Force Kubernetes to always pull the latest image
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
