apiVersion: v1
kind: Service
metadata:
  name: django-todo-service
  labels:
    app: django-todo
spec:
  selector:
    app: django-todo
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30001  
